module.exports = {
  QRCodeReloadSel: '#app > ._1FKgS.app-wrapper-web.bN4GZ > ._2U_Zc > ._2NbD3 > .elDYX > .XSdna > ._2EZ_m._1i65u > span > .HnNfm',
  QRCodeReloadSelFilt: '#app > ._1FKgS.app-wrapper-web.bN4GZ > ._2U_Zc > ._2NbD3 > .elDYX > .XSdna > ._2EZ_m._1i65u > span > .HnNfm.velocity-animating',
  QRCodeSel: '#app > ._1FKgS.app-wrapper-web.bN4GZ > ._2U_Zc > ._2NbD3 > .elDYX > .XSdna > ._2EZ_m > img',
  firstPaneSel: '#app > ._1FKgS.app-wrapper-web.bFqKf > .app._3dqpi.two',
  newNotifSel: '#pane-side._1vDUw._1NrpZ > div > div > .RLfQR > ._2wP_Y > div > ._2EXPL.CxUIE > ._3j7s9 > ._1AwDx > ._3Bxar > span > ._15G96 > span.OUeyt._3zmhL',
  headSel: '#main > header > div._5SiUq > div._16vzP > div > span',
  loadEarlierMessageSel: '#main._1GX8_ > ._3zJZ2 > .copyable-area > ._2nmDZ > ._1MsrQ > ._3dGYA',
  retrySel: '#app > ._1FKgS.app-wrapper-web > div',
  retryButtonSel: '._3QNwO > ._1WZqU.PNlAR[role: "button"]',
  mainSel: '#main._1GX8_',
  startupSel: '#startup > .Pg7Si > progress',
  newChatSel: '#pane-side._1vDUw._1NrpZ > div > div > .RLfQR > ._2wP_Y > div > ._2EXPL.CxUIE > ._3j7s9',
  newNotifSel2: '#pane-side._1vDUw._1NrpZ > div > div > .RLfQR > ._2wP_Y > div > ._2EXPL.CxUIE._1f1zm > ._3j7s9 > ._1AwDx > ._3Bxar > span > ._15G96.velocity-animating > span.OUeyt._3zmhL',
  newNotifSel3: '#pane-side._1vDUw._1NrpZ > div > div > .RLfQR > ._2wP_Y > div > ._2EXPL.CxUIE > ._3j7s9 > ._1AwDx > ._3Bxar > span > ._15G96.velocity-animating > span.OUeyt._3zmhL',
  newNotifSel4: '#pane-side._1vDUw._1NrpZ > div > div > .RLfQR > ._2wP_Y.velocity-animating > div > ._2EXPL.CxUIE > ._3j7s9 > ._1AwDx > ._3Bxar > span > ._15G96.velocity-animating > span.OUeyt._3zmhL',
  newNotifSel5: '#pane-side._1vDUw._1NrpZ > div > div > .RLfQR > ._2wP_Y.velocity-animating > div > ._2EXPL.CxUIE._1f1zm > ._3j7s9 > ._1AwDx > ._3Bxar > span > ._15G96.velocity-animating > span.OUeyt._3zmhL',
  newNotifSel6: '#pane-side._1vDUw._1NrpZ > div > div > .RLfQR > ._2wP_Y > div > ._2EXPL.CxUIE > ._3j7s9 > ._1AwDx > ._3Bxar > span > ._15G96 > span.OUeyt._3zmhL',
  newNotifSel7: '#pane-side._1vDUw._1NrpZ > div > div > .RLfQR > ._2wP_Y > div > ._2EXPL.CxUIE > ._3j7s9 > ._1AwDx > ._3Bxar > span > ._15G96 > span.OUeyt',
  newNotifSel8: '#pane-side._1vDUw._1NrpZ > div > div > .RLfQR > ._2wP_Y > div > ._2EXPL.CxUIE._1f1zm > ._3j7s9 > ._1AwDx > ._3Bxar > span > ._15G96.velocity-animating > span.OUeyt',
  newNotifSel9: '#pane-side._1vDUw._1NrpZ > div > div > .RLfQR > ._2wP_Y > div > ._2EXPL.CxUIE > ._3j7s9 > ._1AwDx > ._3Bxar > span > ._15G96.velocity-animating > span.OUeyt',
  //mainChatSel: '#main > div > div > ._2nmDZ > ._9tCEa > .vW7d1 > .message-in',
  mainChatSel: '#main > div._1_q7u > div > div > div._1ays2 > div > div > div > div > div.copyable-text',

}